# Neden NumPy?

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]

In [3]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [6]:
a * b

array([ 2,  6, 12, 20])

*******************************************
NumPy, normal bir array oluşturmak yerine NumPy array oluşturduğumuzda çok daha iyi performanslı veri tutmayı sağlar.
*******************************************
1-) Optimizasyon ve veri saklama.
2-) High level vektörel operasyonlar ve nümerik hesaplamalar yapma imkanı sağlar.
*******************************************

# NumPy Array'i Oluşturmak

In [7]:
a = np.array([1,2,3,4,5])

In [8]:
type(a)

numpy.ndarray

In [9]:
np.array([3.14,4,2,13], dtype = "int")

array([ 3,  4,  2, 13])

# Sıfırdan Array Oluşturmak

In [10]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3,5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.full((3,5) ,3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [13]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [14]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
np.random.normal(10,4,(3,4))

array([[ 6.92652557,  5.89475279,  7.69338015,  8.05252114],
       [ 8.27680747, 10.36640623, 10.22486495, 15.62616998],
       [11.55671957, 14.66219552, 13.1385981 , 11.26014439]])

In [16]:
np.random.randint(0,10,(3,3))

array([[5, 7, 5],
       [5, 7, 4],
       [0, 6, 5]])

# Özellikleri

* **ndim:** Boyut sayısı
* **shape:** Boyut bilgisi
* **size:** Toplam eleman sayısı
* **dtype:** Array veri tipi

In [17]:
a = np.random.randint(10, size = 10)

In [18]:
a.ndim

1

In [19]:
a.shape

(10,)

In [20]:
a.size

10

In [21]:
a.dtype

dtype('int32')

In [22]:
 b = np.random.randint(10, size = (3,5))

In [23]:
b.ndim

2

In [24]:
b.shape

(3, 5)

In [25]:
b.size

15

In [26]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme (reshaping)

In [27]:
a = np.arange(1,10)

In [28]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
a.ndim

1

# Birleştirme (Concatenation)

In [30]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [31]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [32]:
c = np.array([7,8,9])

In [33]:
np.concatenate([a,b,c])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## İki Boyut

In [34]:
a = np.array([[1,2,3],
              [4,5,6]])

In [35]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [36]:
np.concatenate([a,a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [37]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [38]:
a = np.array([1,2,3,99,99,3,2,1])

In [39]:
np.split(a, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [40]:
x,y,z = np.split(a, [3,5])

In [41]:
print(x)
print(y)
print(z)

[1 2 3]
[99 99]
[3 2 1]


## İki Boyutlu Ayırma

In [42]:
m = np.arange(16).reshape(4,4)

In [43]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [44]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [45]:
r,k = np.vsplit(m, [2])

In [46]:
t,f = np.hsplit(m, [2])

In [47]:
print(r)
print(k)
print(t)
print(f)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Array Sıralama (Sorting)

In [48]:
a = np.array([2,1,4,3,5])

In [49]:
np.sort(a)

array([1, 2, 3, 4, 5])

In [50]:
a.sort()

In [51]:
a

array([1, 2, 3, 4, 5])

## İki Boyutlu Array Sıralama

In [52]:
a = np.random.normal(20,5,(3,3))

In [53]:
np.sort(a , axis = 0) # sütun sıralar

array([[13.59375944, 14.93177401, 18.5459902 ],
       [21.0364037 , 18.94459632, 20.22876575],
       [21.5622376 , 21.33940716, 28.22721517]])

In [54]:
np.sort(a, axis = 1) # satır sıralar

array([[20.22876575, 21.33940716, 21.5622376 ],
       [14.93177401, 21.0364037 , 28.22721517],
       [13.59375944, 18.5459902 , 18.94459632]])

# İndex İle Elemnlara Erişmek

In [55]:
a = np.random.randint(10, size = 10)

In [56]:
a[0] # sıfırıncı indis

4

In [57]:
a[-1] # son indis

8

In [58]:
a[0] = 100 # sıfırıncı indis artık 100

In [59]:
a

array([100,   0,   9,   8,   2,   7,   5,   8,   6,   8])

## İki Boyutlu'da

In [60]:
m = np.random.randint(10, size = (3,5))
m

array([[6, 7, 2, 8, 8],
       [0, 5, 2, 7, 2],
       [7, 0, 4, 1, 8]])

In [61]:
m[0,0] 

6

In [62]:
m[-1,-1]

8

In [63]:
m[0,3] = 13
m

array([[ 6,  7,  2, 13,  8],
       [ 0,  5,  2,  7,  2],
       [ 7,  0,  4,  1,  8]])

In [64]:
m[1,4] = 2.2
m

array([[ 6,  7,  2, 13,  8],
       [ 0,  5,  2,  7,  2],
       [ 7,  0,  4,  1,  8]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [65]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [66]:
a[0:3]

array([20, 21, 22])

In [67]:
a[:3]

array([20, 21, 22])

In [68]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [69]:
a[::2]

array([20, 22, 24, 26, 28])

In [70]:
a[2::2]

array([22, 24, 26, 28])

In [71]:
a[2:7:2]

array([22, 24, 26])

## İki boyutlu slice işlemleri

In [72]:
m = np.random.randint(10, size = (5,5))
m

array([[2, 6, 9, 5, 5],
       [7, 8, 5, 1, 3],
       [3, 3, 9, 5, 8],
       [8, 7, 8, 0, 0],
       [2, 6, 2, 7, 0]])

In [73]:
m[:,0] # sıfırıncı sütunlar

array([2, 7, 3, 8, 2])

In [74]:
m[0,:] # sıfırıncı satırlar

array([2, 6, 9, 5, 5])

In [75]:
m[0] # sıfırıcı satırlar

array([2, 6, 9, 5, 5])

In [76]:
m[0:2,0:3] # sıfırıncı satırda ikiye kadar, sıfırıncı sütundan üçe kadar

array([[2, 6, 9],
       [7, 8, 5]])

In [77]:
m[:,:2] # tüm satırları al, ikiye kadar sütunlar

array([[2, 6],
       [7, 8],
       [3, 3],
       [8, 7],
       [2, 6]])

# Alt Küme Üzerinde İşlem Yapmak

In [78]:
a = np.random.randint(10, size = (5,5))
a

array([[7, 8, 0, 0, 5],
       [0, 8, 7, 6, 3],
       [6, 8, 4, 1, 4],
       [0, 7, 3, 0, 2],
       [0, 3, 0, 4, 2]])

In [79]:
alt_a = a[0:3, 0:2]
alt_a

array([[7, 8],
       [0, 8],
       [6, 8]])

In [81]:
alt_a[0,0] = 99999
alt_a[1,1] = 888
alt_a

array([[99999,     8],
       [    0,   888],
       [    6,     8]])

In [82]:
a

array([[99999,     8,     0,     0,     5],
       [    0,   888,     7,     6,     3],
       [    6,     8,     4,     1,     4],
       [    0,     7,     3,     0,     2],
       [    0,     3,     0,     4,     2]])

In [83]:
m = np.random.randint(10, size = (5,5))
m

array([[1, 8, 4, 1, 6],
       [7, 9, 1, 9, 7],
       [7, 0, 5, 8, 9],
       [6, 5, 0, 1, 0],
       [3, 0, 3, 5, 4]])

In [91]:
alt_m = m[0:3, 0:2].copy() # yanlızca alt kümede değişiklik yaılmasını sağlar
alt_m

array([[1, 8],
       [7, 9],
       [7, 0]])

In [92]:
alt_m[0,0] = 99999
alt_m[1,1] = 888
alt_m

array([[99999,     8],
       [    7,   888],
       [    7,     0]])

In [93]:
m

array([[1, 8, 4, 1, 6],
       [7, 9, 1, 9, 7],
       [7, 0, 5, 8, 9],
       [6, 5, 0, 1, 0],
       [3, 0, 3, 5, 4]])

# Fancy Index ile Elemanlara Erişmek

In [96]:
a = np.arange(0, 30, 3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [97]:
a[1]

3

In [100]:
a[3]

9

In [101]:
a[5]

15

In [102]:
[a[1], a[3], a[5]]

[3, 9, 15]

In [105]:
al_getir = [1,3,5]

In [107]:
a[al_getir] # fancy index

array([ 3,  9, 15])

## İki Boyutta Fancy

In [108]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [112]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [113]:
m[satir, sutun] # fancy iki boyutta index

array([1, 5])

## Basit İndex İle Fancy İndex

In [114]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
m[0, [1 ,2]]

array([1, 2])

## Slice İle Fancy

In [117]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [118]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [119]:
a > 5

array([False, False, False, False, False])

In [120]:
a < 3

array([ True,  True, False, False, False])

In [121]:
a[a < 3]

array([1, 2])

In [122]:
a[a > 3]

array([4, 5])

In [123]:
a[a >= 3]

array([3, 4, 5])

In [124]:
a[a <= 3]

array([1, 2, 3])

In [125]:
a[a == 3]

array([3])

In [126]:
a[a != 3]

array([1, 2, 4, 5])

In [127]:
a * 2

array([ 2,  4,  6,  8, 10])

In [128]:
a / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [129]:
a*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [133]:
a**2

array([ 1,  4,  9, 16, 25])

# Matematiksel İşlemler

In [136]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [138]:
a - 1

array([0, 1, 2, 3, 4])

In [139]:
a * 5

array([ 5, 10, 15, 20, 25])

In [140]:
a / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [142]:
a * 5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

## ufunc

In [144]:
np.subtract(a, 1)

array([0, 1, 2, 3, 4])

In [145]:
np.add(a, 1)

array([2, 3, 4, 5, 6])

In [146]:
np.multiply(a, 5)

array([ 5, 10, 15, 20, 25])

In [147]:
np.divide(a, 5)

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [148]:
np.power(a, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [149]:
np.mod(a, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [150]:
np.absolute(np.array([-3, -10, 11]))

array([ 3, 10, 11])

In [157]:
np.sin(75)

-0.38778163540943045

In [152]:
np.cos(30)

0.15425144988758405

In [159]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [160]:
np.log2(a)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [161]:
np.log10(10)

1.0

In [162]:
?np # help np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Taha\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\taha\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x

In [164]:
np.mean(a)

3.0

In [165]:
a.sum()

15

In [167]:
a.min()

1

In [168]:
a.max()

5

In [171]:
np.var(a)

2.0

In [172]:
np.std(a)

1.4142135623730951

# NumPy ile İki Bilinmeyenli Denklem Çözümü

5 * x0 + x1 = 12 &
x0 + 3 * x1 = 10

In [175]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [177]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])